
export const filterArr =  [
    {
        id: 1,
        placholder : "Product Code",
        type: "text",
        name: "productCode",
        className: "input-class",
        value: null,
    },{
        id: 2,
        placholder : "Product Barcode",
        type: "text",
        name: "productBarcode",
        className: "input-class",
        value: null,
    },{
        id: 3,
        placholder : "Product Name",
        type: "text",
        name: "productName",
        className: "input-class",
        value: null,
    },{
        id: 4,
        placholder : "Petzz Price",
        type: "text",
        name: "petzzPrice",
        className: "input-class",
        value: null,
    },{
        id: 5,
        placholder : "Low Price",
        type: "number",
        name: "lowPrice",
        className: "input-class",
        value: null,
    },{
        id: 6,
        placholder : "High Price",
        type: "number",
        name: "highPrice",
        className: "input-class",
        value: null,
    },{
        id: 7,
        placholder : "Drop Price",
        type: "number",
        name: "dropPrice",
        className: "input-class",
        value: null,
    },{
        id: 8,
        placholder : "Target Price",
        type: "number",
        name: "targetPrice",
        className: "input-class",
        value: null,
    },{
        id: 9,
        placholder : "Conts Price",
        type: "number",
        name: "constPrice",
        className: "input-class",
        value: null,
    },
]


export const data = {
    "data": [
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "productName": "Eymen",
        "productCode": "31",
        "productBarcode": "string",
        "productUrl": "string",
        "akakceUrl": "string",
        "brandName": "string",
        "mainCategory": "string",
        "subCategory": "string",
        "subSubCategory": "string",
        "lowPrice": 0,
        "highPrice": 0,
        "petzzPrice": 0,
        "constPrice": 0,
        "dropPrice": 0,
        "targetPrice": 0,
        "createdAt": "2023-06-05T16:35:52.473Z",
        "updatedAt": "2023-06-05T16:35:52.473Z",
      },
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "productName": "Demir",
        "productCode": "69",
        "productBarcode": "string",
        "productUrl": "string",
        "akakceUrl": "string",
        "brandName": "string",
        "mainCategory": "string",
        "subCategory": "string",
        "subSubCategory": "string",
        "lowPrice": 0,
        "highPrice": 0,
        "petzzPrice": 0,
        "constPrice": 0,
        "dropPrice": 0,
        "targetPrice": 0,
        "createdAt": "2023-06-05T16:35:52.473Z",
        "updatedAt": "2023-06-05T16:35:52.473Z",
      },
      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "productName": "Yusuf",
        "productCode": "35",
        "productBarcode": "string",
        "productUrl": "string",
        "akakceUrl": "string",
        "brandName": "string",
        "mainCategory": "string",
        "subCategory": "string",
        "subSubCategory": "string",
        "lowPrice": 0,
        "highPrice": 0,
        "petzzPrice": 0,
        "constPrice": 0,
        "dropPrice": 0,
        "targetPrice": 0,
        "createdAt": "2023-06-05T16:35:52.473Z",
        "updatedAt": "2023-06-05T16:35:52.473Z",
      },

      {
        "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "productName": "Yusuf",
        "productCode": "41",
        "productBarcode": "string",
        "productUrl": "string",
        "akakceUrl": "string",
        "brandName": "string",
        "mainCategory": "string",
        "subCategory": "string",
        "subSubCategory": "string",
        "lowPrice": 0,
        "highPrice": 0,
        "petzzPrice": 0,
        "constPrice": 0,
        "dropPrice": 0,
        "targetPrice": 0,
        "createdAt": "2023-06-05T16:35:52.473Z",
        "updatedAt": "2023-06-05T16:35:52.473Z",
      }
    ],
    "isSuccessful": true,
    "errors": [
      "string"
    ]
  }